:stem: latexmath

[#mathematical-formulation]
=== Mathematical Formulation

The DAE layered standard version `1.0.0-alpha.1` is intentionally restricted to *semi-explicit index-1 DAEs* used with FMI Model Exchange during *https://fmi-standard.org/docs/3.0.2/#ContinuousTimeMode[Continuous-Time Mode]*.

The supported formulation of DAEs is

[latexmath]
++++
\dot{\mathbf{x}}_c = \mathbf{f}_{\mathit{der}}(\mathbf{x}_c, \mathbf{a}_c, \mathbf{u}_c, \mathbf{p}, t)
++++

[latexmath]
++++
0 = \mathbf{f}_{\mathit{res}}(\mathbf{x}_c, \mathbf{a}_c, \mathbf{u}_c, \mathbf{p}, t)
++++

[latexmath]
++++
\mathbf{y} = \mathbf{f}_{\mathit{out}}(\mathbf{x}_c, \mathbf{a}_c, \mathbf{u}_c, \mathbf{p}, t)
++++

where:

* latexmath:[\mathbf{x}_c] denotes the continuous-time https://fmi-standard.org/docs/3.0.2/#state[states],
* latexmath:[\dot{\mathbf{x}}_c] denotes the continuous-state https://fmi-standard.org/docs/3.0.2/#ContinuousStateDerivative[derivatives],
* latexmath:[\mathbf{a}_c] denotes the <<AlgebraicVariable, algebraic variables>>,
* latexmath:[\mathbf{u}_c] denotes the continuous-time https://fmi-standard.org/docs/3.0.2/#input[inputs],
* latexmath:[\mathbf{p}] denotes the https://fmi-standard.org/docs/3.0.2/#parameter[parameters],
* latexmath:[t] denotes time,
* latexmath:[\mathbf{f}_{\mathit{res}}] denotes the algebraic equations expressed as <<Residual, residuals>>, and
* latexmath:[\mathbf{y}] denotes the https://fmi-standard.org/docs/3.0.2/#output[outputs].

The equations latexmath:[\dot{\mathbf{x}}_c = \mathbf{f}_{\mathit{der}}(\mathbf{x}_c,\mathbf{a}_c,\mathbf{u}_c,\mathbf{p},t)] are the differential equations of the model, which can be acquired with the usual way of either

* calling https://fmi-standard.org/docs/3.0.2/#get-and-set-variable-values[`fmi3Get`] on the derivative variables provided in the extended <<ModelStructure>> defined in <<layered-standard-manifest-file>> , or
* calling https://fmi-standard.org/docs/3.0.2/#fmi3GetContinuousStateDerivatives[`fmi3GetContinuousStateDerivatives`].

The equations latexmath:[0 = \mathbf{f}_{\mathit{res}}(\mathbf{x}_c,\mathbf{a}_c,\mathbf{u}_c,\mathbf{p},t)] are represented in the FMU by <<Residual, residual>> variables and constrain the algebraic variables together with the other continuous-time variables of the model. These can be acquired by calling https://fmi-standard.org/docs/3.0.2/#get-and-set-variable-values[`fmi3Get`] on the <<Residual, residual>> variables provided in the extended <<ModelStructure>> defined in <<layered-standard-manifest-file>>.

For the DAE to be index 1 in this layered standard means that the algebraic equations must be solvable for the algebraic variables. In particular, the Jacobian of the algebraic equations with respect to the algebraic variables must be non-singular.

Consequently, for given values of latexmath:[\mathbf{x}_c], latexmath:[\mathbf{u}_c], latexmath:[\mathbf{p}], and latexmath:[t], the algebraic equations determine latexmath:[\mathbf{a}_c]. The importer is responsible for determining values of the algebraic variables that satisfy

[latexmath]
++++
\mathbf{f}_{\mathit{res}}(\mathbf{x}_c,\mathbf{a}_c,\mathbf{u}_c,t,\mathbf{p}) = 0
++++

while the FMU provides the continuous-state derivatives and outputs according to the equations above.

This version of the layered standard does not define support for more general DAE formulations, including fully implicit DAEs, higher-index DAEs, or formulations that require differentiation of algebraic constraints. Such formulations must first be transformed into the supported semi-explicit index-1 form before they can be represented by this version of the layered standard.

The DAE formulation defined by this layered standard applies only while the Model Exchange FMU is in *https://fmi-standard.org/docs/3.0.2/#ContinuousTimeMode[Continuous-Time Mode]*. Behavior associated with discontinuities, event handling, and DAE formulations outside Continuous Time Mode is outside the scope of version `1.0.0-alpha.1`.
